export enum AccountCategory {
  TaiSan = 1,
  NoPhaiTra = 2,
  VonChuSoHuu = 3,
  DoanhThu = 4,
  ChiPhi = 5,
  XacDinhKetQua = 6,
}

export enum AccountNature {
  DuNo = 1,
  DuCo = 2,
  LuongTinh = 3,
  KhongCoSoDu = 4,
}

export enum AccountType {
  TaiKhoanMe = 1,
  TaiKhoanCon = 2,
  TaiKhoanChiTiet = 3,
}

export enum JournalEntryType {
  ThuTien = 1,
  ChiTien = 2,
  ThuNganHang = 3,
  ChiNganHang = 4,
  MuaHang = 5,
  BanHang = 6,
  KhauHao = 7,
  PhanBo = 8,
  TongHop = 9,
  DieuChinh = 10,
  KetChuyen = 11,
  KhoaSo = 12,
  Khac = 99,
}

export enum FiscalPeriodStatus {
  Open = 1,
  Closed = 2,
  Locked = 3,
}

export function getAccountCategoryLabel(c: AccountCategory): string {
  const labels: Record<AccountCategory, string> = {
    [AccountCategory.TaiSan]: 'Tài sản',
    [AccountCategory.NoPhaiTra]: 'Nợ phải trả',
    [AccountCategory.VonChuSoHuu]: 'Vốn chủ sở hữu',
    [AccountCategory.DoanhThu]: 'Doanh thu',
    [AccountCategory.ChiPhi]: 'Chi phí',
    [AccountCategory.XacDinhKetQua]: 'Xác định kết quả kinh doanh',
  };
  return labels[c];
}

export function getAccountNatureLabel(n: AccountNature): string {
  const labels: Record<AccountNature, string> = {
    [AccountNature.DuNo]: 'Dư Nợ',
    [AccountNature.DuCo]: 'Dư Có',
    [AccountNature.LuongTinh]: 'Lưỡng tính',
    [AccountNature.KhongCoSoDu]: 'Không có số dư',
  };
  return labels[n];
}

export function getJournalEntryTypeLabel(t: JournalEntryType): string {
  const labels: Record<JournalEntryType, string> = {
    [JournalEntryType.ThuTien]: 'Phiếu thu',
    [JournalEntryType.ChiTien]: 'Phiếu chi',
    [JournalEntryType.ThuNganHang]: 'Giấy báo Có',
    [JournalEntryType.ChiNganHang]: 'Giấy báo Nợ',
    [JournalEntryType.MuaHang]: 'Hóa đơn mua hàng',
    [JournalEntryType.BanHang]: 'Hóa đơn bán hàng',
    [JournalEntryType.KhauHao]: 'Khấu hao TSCĐ',
    [JournalEntryType.PhanBo]: 'Phân bổ CCDC',
    [JournalEntryType.TongHop]: 'Chứng từ tổng hợp',
    [JournalEntryType.DieuChinh]: 'Điều chỉnh',
    [JournalEntryType.KetChuyen]: 'Kết chuyển',
    [JournalEntryType.KhoaSo]: 'Khóa sổ',
    [JournalEntryType.Khac]: 'Khác',
  };
  return labels[t];
}

export function getFiscalPeriodStatusLabel(s: FiscalPeriodStatus): string {
  const labels: Record<FiscalPeriodStatus, string> = {
    [FiscalPeriodStatus.Open]: 'Đang mở',
    [FiscalPeriodStatus.Closed]: 'Đã khóa sổ',
    [FiscalPeriodStatus.Locked]: 'Đã khóa',
  };
  return labels[s];
}

export const ACCOUNT_CATEGORY_NATURE: Record<AccountCategory, AccountNature> = {
  [AccountCategory.TaiSan]: AccountNature.DuNo,
  [AccountCategory.NoPhaiTra]: AccountNature.DuCo,
  [AccountCategory.VonChuSoHuu]: AccountNature.DuCo,
  [AccountCategory.DoanhThu]: AccountNature.DuCo,
  [AccountCategory.ChiPhi]: AccountNature.DuNo,
  [AccountCategory.XacDinhKetQua]: AccountNature.LuongTinh,
};

export const STANDARD_ACCOUNTS: Array<{ number: string; name: string; category: AccountCategory; parent?: string }> = [
  { number: '1', name: 'Tài sản ngắn hạn', category: AccountCategory.TaiSan },
  { number: '11', name: 'Tiền và các khoản tương đương tiền', category: AccountCategory.TaiSan, parent: '1' },
  { number: '111', name: 'Tiền mặt', category: AccountCategory.TaiSan, parent: '11' },
  { number: '1111', name: 'Tiền Việt Nam', category: AccountCategory.TaiSan, parent: '111' },
  { number: '1112', name: 'Ngoại tệ', category: AccountCategory.TaiSan, parent: '111' },
  { number: '1113', name: 'Vàng bạc, kim khí, đá quý', category: AccountCategory.TaiSan, parent: '111' },
  { number: '112', name: 'Tiền gửi ngân hàng', category: AccountCategory.TaiSan, parent: '11' },
  { number: '1121', name: 'Tiền Việt Nam', category: AccountCategory.TaiSan, parent: '112' },
  { number: '1122', name: 'Ngoại tệ', category: AccountCategory.TaiSan, parent: '112' },
  { number: '113', name: 'Tiền đang chuyển', category: AccountCategory.TaiSan, parent: '11' },
  { number: '12', name: 'Đầu tư tài chính ngắn hạn', category: AccountCategory.TaiSan, parent: '1' },
  { number: '121', name: 'Chứng khoán kinh doanh', category: AccountCategory.TaiSan, parent: '12' },
  { number: '128', name: 'Đầu tư nắm giữ đến ngày đáo hạn', category: AccountCategory.TaiSan, parent: '12' },
  { number: '13', name: 'Phải thu ngắn hạn', category: AccountCategory.TaiSan, parent: '1' },
  { number: '131', name: 'Phải thu khách hàng', category: AccountCategory.TaiSan, parent: '13' },
  { number: '133', name: 'Thuế GTGT được khấu trừ', category: AccountCategory.TaiSan, parent: '13' },
  { number: '1331', name: 'Thuế GTGT được khấu trừ hàng hóa, dịch vụ', category: AccountCategory.TaiSan, parent: '133' },
  { number: '1332', name: 'Thuế GTGT được khấu trừ TSCĐ', category: AccountCategory.TaiSan, parent: '133' },
  { number: '136', name: 'Phải thu nội bộ', category: AccountCategory.TaiSan, parent: '13' },
  { number: '138', name: 'Phải thu khác', category: AccountCategory.TaiSan, parent: '13' },
  { number: '1381', name: 'Tài sản thiếu chờ xử lý', category: AccountCategory.TaiSan, parent: '138' },
  { number: '1385', name: 'Phải thu về cổ phần hóa', category: AccountCategory.TaiSan, parent: '138' },
  { number: '1388', name: 'Phải thu khác', category: AccountCategory.TaiSan, parent: '138' },
  { number: '14', name: 'Hàng tồn kho', category: AccountCategory.TaiSan, parent: '1' },
  { number: '141', name: 'Tạm ứng', category: AccountCategory.TaiSan, parent: '14' },
  { number: '142', name: 'Chi phí trả trước ngắn hạn', category: AccountCategory.TaiSan, parent: '14' },
  { number: '151', name: 'Hàng mua đang đi đường', category: AccountCategory.TaiSan, parent: '14' },
  { number: '152', name: 'Nguyên vật liệu', category: AccountCategory.TaiSan, parent: '14' },
  { number: '153', name: 'Công cụ, dụng cụ', category: AccountCategory.TaiSan, parent: '14' },
  { number: '154', name: 'Chi phí sản xuất kinh doanh dở dang', category: AccountCategory.TaiSan, parent: '14' },
  { number: '155', name: 'Thành phẩm', category: AccountCategory.TaiSan, parent: '14' },
  { number: '156', name: 'Hàng hóa', category: AccountCategory.TaiSan, parent: '14' },
  { number: '157', name: 'Hàng gửi bán', category: AccountCategory.TaiSan, parent: '14' },
  { number: '158', name: 'Hàng hóa kho bảo thuế', category: AccountCategory.TaiSan, parent: '14' },
  { number: '2', name: 'Tài sản dài hạn', category: AccountCategory.TaiSan },
  { number: '21', name: 'Phải thu dài hạn', category: AccountCategory.TaiSan, parent: '2' },
  { number: '211', name: 'TSCĐ hữu hình', category: AccountCategory.TaiSan, parent: '2' },
  { number: '2111', name: 'Nhà cửa, vật kiến trúc', category: AccountCategory.TaiSan, parent: '211' },
  { number: '2112', name: 'Máy móc, thiết bị', category: AccountCategory.TaiSan, parent: '211' },
  { number: '2113', name: 'Phương tiện vận tải', category: AccountCategory.TaiSan, parent: '211' },
  { number: '2114', name: 'Thiết bị, dụng cụ quản lý', category: AccountCategory.TaiSan, parent: '211' },
  { number: '2115', name: 'Cây lâu năm, súc vật làm việc', category: AccountCategory.TaiSan, parent: '211' },
  { number: '2118', name: 'TSCĐ khác', category: AccountCategory.TaiSan, parent: '211' },
  { number: '212', name: 'TSCĐ thuê tài chính', category: AccountCategory.TaiSan, parent: '2' },
  { number: '213', name: 'TSCĐ vô hình', category: AccountCategory.TaiSan, parent: '2' },
  { number: '2131', name: 'Quyền sử dụng đất', category: AccountCategory.TaiSan, parent: '213' },
  { number: '2132', name: 'Quyền phát hành', category: AccountCategory.TaiSan, parent: '213' },
  { number: '2133', name: 'Bản quyền, bằng sáng chế', category: AccountCategory.TaiSan, parent: '213' },
  { number: '2134', name: 'Nhãn hiệu', category: AccountCategory.TaiSan, parent: '213' },
  { number: '2135', name: 'Phần mềm máy tính', category: AccountCategory.TaiSan, parent: '213' },
  { number: '214', name: 'Hao mòn TSCĐ', category: AccountCategory.TaiSan, parent: '2' },
  { number: '2141', name: 'Hao mòn TSCĐ hữu hình', category: AccountCategory.TaiSan, parent: '214' },
  { number: '2142', name: 'Hao mòn TSCĐ thuê tài chính', category: AccountCategory.TaiSan, parent: '214' },
  { number: '2143', name: 'Hao mòn TSCĐ vô hình', category: AccountCategory.TaiSan, parent: '214' },
  { number: '217', name: 'Bất động sản đầu tư', category: AccountCategory.TaiSan, parent: '2' },
  { number: '221', name: 'Đầu tư vào công ty con', category: AccountCategory.TaiSan, parent: '2' },
  { number: '222', name: 'Đầu tư vào công ty liên kết', category: AccountCategory.TaiSan, parent: '2' },
  { number: '228', name: 'Đầu tư dài hạn khác', category: AccountCategory.TaiSan, parent: '2' },
  { number: '229', name: 'Dự phòng giảm giá tài sản', category: AccountCategory.TaiSan, parent: '2' },
  { number: '241', name: 'Xây dựng cơ bản dở dang', category: AccountCategory.TaiSan, parent: '2' },
  { number: '242', name: 'Chi phí trả trước dài hạn', category: AccountCategory.TaiSan, parent: '2' },
  { number: '243', name: 'Tài sản thuế thu nhập hoãn lại', category: AccountCategory.TaiSan, parent: '2' },
  { number: '3', name: 'Nợ phải trả', category: AccountCategory.NoPhaiTra },
  { number: '31', name: 'Nợ ngắn hạn', category: AccountCategory.NoPhaiTra, parent: '3' },
  { number: '311', name: 'Vay ngắn hạn', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '315', name: 'Nợ thuê tài chính ngắn hạn', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '331', name: 'Phải trả người bán', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '333', name: 'Thuế và các khoản phải nộp Nhà nước', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '3331', name: 'Thuế GTGT phải nộp', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3332', name: 'Thuế tiêu thụ đặc biệt', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3333', name: 'Thuế xuất, nhập khẩu', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3334', name: 'Thuế thu nhập doanh nghiệp', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3335', name: 'Thuế thu nhập cá nhân', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3336', name: 'Thuế tài nguyên', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3337', name: 'Thuế nhà đất', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3338', name: 'Thuế bảo vệ môi trường', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '3339', name: 'Phí, lệ phí và các khoản phải nộp khác', category: AccountCategory.NoPhaiTra, parent: '333' },
  { number: '334', name: 'Phải trả người lao động', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '335', name: 'Chi phí phải trả', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '336', name: 'Phải trả nội bộ', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '337', name: 'Thanh toán theo tiến độ hợp đồng xây dựng', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '338', name: 'Phải trả, phải nộp khác', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '3381', name: 'Tài sản thừa chờ giải quyết', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3382', name: 'Kinh phí công đoàn', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3383', name: 'Bảo hiểm xã hội', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3384', name: 'Bảo hiểm y tế', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3385', name: 'Bảo hiểm thất nghiệp', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3386', name: 'Nhận ký quỹ, ký cược', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3387', name: 'Doanh thu chưa thực hiện', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '3388', name: 'Phải trả khác', category: AccountCategory.NoPhaiTra, parent: '338' },
  { number: '341', name: 'Vay dài hạn', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '343', name: 'Trái phiếu phát hành', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '344', name: 'Nhận ký quỹ, ký cược dài hạn', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '347', name: 'Thuế thu nhập hoãn lại phải trả', category: AccountCategory.NoPhaiTra, parent: '31' },
  { number: '35', name: 'Dự phòng nợ phải trả', category: AccountCategory.NoPhaiTra, parent: '3' },
  { number: '352', name: 'Dự phòng phải trả', category: AccountCategory.NoPhaiTra, parent: '35' },
  { number: '4', name: 'Vốn chủ sở hữu', category: AccountCategory.VonChuSoHuu },
  { number: '411', name: 'Vốn đầu tư của chủ sở hữu', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '4111', name: 'Vốn góp của chủ sở hữu', category: AccountCategory.VonChuSoHuu, parent: '411' },
  { number: '4112', name: 'Thặng dư vốn cổ phần', category: AccountCategory.VonChuSoHuu, parent: '411' },
  { number: '4118', name: 'Vốn khác', category: AccountCategory.VonChuSoHuu, parent: '411' },
  { number: '412', name: 'Chênh lệch đánh giá lại tài sản', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '413', name: 'Chênh lệch tỷ giá hối đoái', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '414', name: 'Quỹ đầu tư phát triển', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '415', name: 'Quỹ dự phòng tài chính', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '416', name: 'Quỹ khen thưởng, phúc lợi', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '417', name: 'Quỹ ổn định thu nhập', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '418', name: 'Các quỹ khác thuộc vốn chủ sở hữu', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '419', name: 'Cổ phiếu quỹ', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '421', name: 'Lợi nhuận chưa phân phối', category: AccountCategory.VonChuSoHuu, parent: '4' },
  { number: '4211', name: 'Lợi nhuận chưa phân phối năm trước', category: AccountCategory.VonChuSoHuu, parent: '421' },
  { number: '4212', name: 'Lợi nhuận chưa phân phối năm nay', category: AccountCategory.VonChuSoHuu, parent: '421' },
  { number: '5', name: 'Doanh thu', category: AccountCategory.DoanhThu },
  { number: '511', name: 'Doanh thu bán hàng và cung cấp dịch vụ', category: AccountCategory.DoanhThu, parent: '5' },
  { number: '5111', name: 'Doanh thu bán hàng hóa', category: AccountCategory.DoanhThu, parent: '511' },
  { number: '5112', name: 'Doanh thu bán thành phẩm', category: AccountCategory.DoanhThu, parent: '511' },
  { number: '5113', name: 'Doanh thu cung cấp dịch vụ', category: AccountCategory.DoanhThu, parent: '511' },
  { number: '5118', name: 'Doanh thu khác', category: AccountCategory.DoanhThu, parent: '511' },
  { number: '515', name: 'Doanh thu hoạt động tài chính', category: AccountCategory.DoanhThu, parent: '5' },
  { number: '521', name: 'Các khoản giảm trừ doanh thu', category: AccountCategory.DoanhThu, parent: '5' },
  { number: '5211', name: 'Chiết khấu thương mại', category: AccountCategory.DoanhThu, parent: '521' },
  { number: '5212', name: 'Hàng bán bị trả lại', category: AccountCategory.DoanhThu, parent: '521' },
  { number: '5213', name: 'Giảm giá hàng bán', category: AccountCategory.DoanhThu, parent: '521' },
  { number: '6', name: 'Chi phí sản xuất, kinh doanh', category: AccountCategory.ChiPhi },
  { number: '611', name: 'Chi phí nguyên liệu, vật liệu trực tiếp', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '621', name: 'Chi phí nhân công trực tiếp', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '622', name: 'Chi phí nhân công trực tiếp', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '623', name: 'Chi phí sử dụng máy thi công', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '627', name: 'Chi phí sản xuất chung', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '6271', name: 'Chi phí nhân viên phân xưởng', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '6272', name: 'Chi phí vật liệu', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '6273', name: 'Chi phí dụng cụ sản xuất', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '6274', name: 'Chi phí khấu hao TSCĐ', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '6277', name: 'Chi phí dịch vụ mua ngoài', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '6278', name: 'Chi phí bằng tiền khác', category: AccountCategory.ChiPhi, parent: '627' },
  { number: '631', name: 'Giá thành sản xuất', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '632', name: 'Giá vốn hàng bán', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '635', name: 'Chi phí tài chính', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '641', name: 'Chi phí bán hàng', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '6411', name: 'Chi phí nhân viên bán hàng', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6412', name: 'Chi phí vật liệu, bao bì', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6413', name: 'Chi phí dụng cụ, đồ dùng', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6414', name: 'Chi phí khấu hao TSCĐ', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6415', name: 'Chi phí bảo hành', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6417', name: 'Chi phí dịch vụ mua ngoài', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '6418', name: 'Chi phí bằng tiền khác', category: AccountCategory.ChiPhi, parent: '641' },
  { number: '642', name: 'Chi phí quản lý doanh nghiệp', category: AccountCategory.ChiPhi, parent: '6' },
  { number: '6421', name: 'Chi phí nhân viên quản lý', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6422', name: 'Chi phí vật liệu quản lý', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6423', name: 'Chi phí đồ dùng văn phòng', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6424', name: 'Chi phí khấu hao TSCĐ', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6425', name: 'Thuế, phí, lệ phí', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6426', name: 'Chi phí dự phòng', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6427', name: 'Chi phí dịch vụ mua ngoài', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '6428', name: 'Chi phí bằng tiền khác', category: AccountCategory.ChiPhi, parent: '642' },
  { number: '7', name: 'Thu nhập khác', category: AccountCategory.ChiPhi },
  { number: '711', name: 'Thu nhập khác', category: AccountCategory.ChiPhi, parent: '7' },
  { number: '8', name: 'Xác định kết quả kinh doanh', category: AccountCategory.XacDinhKetQua },
  { number: '811', name: 'Chi phí thuế thu nhập doanh nghiệp', category: AccountCategory.XacDinhKetQua, parent: '8' },
  { number: '821', name: 'Chi phí thuế thu nhập doanh nghiệp', category: AccountCategory.XacDinhKetQua, parent: '8' },
  { number: '911', name: 'Xác định kết quả kinh doanh', category: AccountCategory.XacDinhKetQua, parent: '8' },
];
