import type { Database } from 'better-sqlite3';

export interface VSICEntry {
  code: string;
  level: number;
  name: string;
  parentCode: string | null;
}

export const VSIC_SEED_DATA: VSICEntry[] = [
  { code: 'A', level: 1, name: 'Nông nghiệp, lâm nghiệp và thủy sản', parentCode: null },
  { code: 'B', level: 1, name: 'Khai khoáng', parentCode: null },
  { code: 'C', level: 1, name: 'Công nghiệp chế biến, chế tạo', parentCode: null },
  { code: 'D', level: 1, name: 'Sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hòa không khí', parentCode: null },
  { code: 'E', level: 1, name: 'Cung cấp nước; hoạt động quản lý và xử lý rác thải, nước thải', parentCode: null },
  { code: 'F', level: 1, name: 'Xây dựng', parentCode: null },
  { code: 'G', level: 1, name: 'Bán buôn và bán lẻ; sửa chữa ô tô, mô tô, xe máy và xe có động cơ khác', parentCode: null },
  { code: 'H', level: 1, name: 'Vận tải kho bãi', parentCode: null },
  { code: 'I', level: 1, name: 'Dịch vụ lưu trú và ăn uống', parentCode: null },
  { code: 'J', level: 1, name: 'Thông tin và truyền thông', parentCode: null },
  { code: 'K', level: 1, name: 'Hoạt động tài chính, ngân hàng và bảo hiểm', parentCode: null },
  { code: 'L', level: 1, name: 'Hoạt động kinh doanh bất động sản', parentCode: null },
  { code: 'M', level: 1, name: 'Hoạt động chuyên môn, khoa học và công nghệ', parentCode: null },
  { code: 'N', level: 1, name: 'Hoạt động hành chính và dịch vụ hỗ trợ', parentCode: null },
  { code: 'O', level: 1, name: 'Hoạt động của Đảng Cộng sản, tổ chức chính trị - xã hội, quản lý nhà nước, an ninh quốc phòng', parentCode: null },
  { code: 'P', level: 1, name: 'Giáo dục và đào tạo', parentCode: null },
  { code: 'Q', level: 1, name: 'Y tế và hoạt động trợ giúp xã hội', parentCode: null },
  { code: 'R', level: 1, name: 'Nghệ thuật, vui chơi và giải trí', parentCode: null },
  { code: 'S', level: 1, name: 'Hoạt động dịch vụ khác', parentCode: null },
  { code: 'T', level: 1, name: 'Hoạt động làm thuê các công việc trong các hộ gia đình, sản xuất sản phẩm vật chất và dịch vụ tự tiêu dùng của hộ gia đình', parentCode: null },
  { code: 'U', level: 1, name: 'Hoạt động của các tổ chức và cơ quan quốc tế', parentCode: null },
  { code: '01110', level: 4, name: 'Trồng lúa', parentCode: 'A' },
  { code: '01120', level: 4, name: 'Trồng ngô và cây lương thực khác', parentCode: 'A' },
  { code: '01130', level: 4, name: 'Trồng rau, đậu các loại và trồng hoa, cây cảnh', parentCode: 'A' },
  { code: '01140', level: 4, name: 'Trồng cây mía', parentCode: 'A' },
  { code: '01150', level: 4, name: 'Trồng cây thuốc lá, thuốc lào', parentCode: 'A' },
  { code: '01160', level: 4, name: 'Trồng cây lấy sợi', parentCode: 'A' },
  { code: '10100', level: 4, name: 'Chế biến, bảo quản thịt và các sản phẩm từ thịt', parentCode: 'C' },
  { code: '10200', level: 4, name: 'Chế biến, bảo quản thủy sản và các sản phẩm từ thủy sản', parentCode: 'C' },
  { code: '10300', level: 4, name: 'Chế biến và bảo quản rau quả', parentCode: 'C' },
  { code: '10400', level: 4, name: 'Sản xuất dầu, mỡ động, thực vật', parentCode: 'C' },
  { code: '10500', level: 4, name: 'Chế biến sữa và các sản phẩm từ sữa', parentCode: 'C' },
  { code: '10610', level: 4, name: 'Xay xát và sản xuất bột', parentCode: 'C' },
  { code: '10710', level: 4, name: 'Sản xuất bánh mỳ, bánh ngọt, bánh quy và các loại bánh khô khác', parentCode: 'C' },
  { code: '10720', level: 4, name: 'Sản xuất đường', parentCode: 'C' },
  { code: '10730', level: 4, name: 'Sản xuất ca cao, sôcôla và bánh kẹo', parentCode: 'C' },
  { code: '10740', level: 4, name: 'Sản xuất mì ống, mỳ sợi và sản phẩm tương tự', parentCode: 'C' },
  { code: '10750', level: 4, name: 'Sản xuất thực phẩm khác chưa được phân vào đâu', parentCode: 'C' },
  { code: '10760', level: 4, name: 'Sản xuất thức ăn gia súc, gia cầm và thủy sản', parentCode: 'C' },
  { code: '10800', level: 4, name: 'Sản xuất thức ăn chăn nuôi', parentCode: 'C' },
  { code: '11010', level: 4, name: 'Sản xuất đồ uống không cồn, nước khoáng', parentCode: 'C' },
  { code: '11020', level: 4, name: 'Sản xuất bia và mạch nha ủ men bia', parentCode: 'C' },
  { code: '11030', level: 4, name: 'Sản xuất rượu vang', parentCode: 'C' },
  { code: '11040', level: 4, name: 'Sản xuất rượu mạnh và rượu các loại khác', parentCode: 'C' },
  { code: '13110', level: 4, name: 'Sản xuất sợi dệt', parentCode: 'C' },
  { code: '13120', level: 4, name: 'Dệt vải', parentCode: 'C' },
  { code: '13130', level: 4, name: 'Hoàn thiện vải', parentCode: 'C' },
  { code: '14110', level: 4, name: 'Sản xuất trang phục ngoại trừ trang phục độn lông, da', parentCode: 'C' },
  { code: '14120', level: 4, name: 'Sản xuất trang phục độn lông, da', parentCode: 'C' },
  { code: '14130', level: 4, name: 'Sản xuất hàng may sẵn', parentCode: 'C' },
  { code: '15110', level: 4, name: 'Thuộc da, sơ chế da', parentCode: 'C' },
  { code: '15120', level: 4, name: 'Sản xuất vali, túi xách, yên đệm', parentCode: 'C' },
  { code: '15200', level: 4, name: 'Sản xuất giày, dép', parentCode: 'C' },
  { code: '16100', level: 4, name: 'Xẻ, bào gỗ và bảo quản gỗ', parentCode: 'C' },
  { code: '16210', level: 4, name: 'Sản xuất ván ép, ván mỏng, ván dăm và ván sợi', parentCode: 'C' },
  { code: '16220', level: 4, name: 'Sản xuất đồ gỗ xây dựng', parentCode: 'C' },
  { code: '16230', level: 4, name: 'Sản xuất đồ gỗ khác', parentCode: 'C' },
  { code: '18110', level: 4, name: 'In ấn', parentCode: 'C' },
  { code: '18120', level: 4, name: 'Hoạt động dịch vụ liên quan đến in', parentCode: 'C' },
  { code: '18200', level: 4, name: 'Sao chép bản ghi các loại', parentCode: 'C' },
  { code: '19100', level: 4, name: 'Sản xuất than cốc', parentCode: 'C' },
  { code: '19200', level: 4, name: 'Sản xuất sản phẩm dầu mỏ tinh chế', parentCode: 'C' },
  { code: '20110', level: 4, name: 'Sản xuất hóa chất cơ bản', parentCode: 'C' },
  { code: '20120', level: 4, name: 'Sản xuất phân bón và hợp chất nitơ', parentCode: 'C' },
  { code: '20130', level: 4, name: 'Sản xuất chất dẻo và cao su tổng hợp', parentCode: 'C' },
  { code: '20210', level: 4, name: 'Sản xuất thuốc bảo vệ thực vật', parentCode: 'C' },
  { code: '20220', level: 4, name: 'Sản xuất sơn, vecni và các chất sơn phủ tương tự', parentCode: 'C' },
  { code: '20230', level: 4, name: 'Sản xuất mỹ phẩm, xà phòng, chất tẩy rửa, chất bóng và chế phẩm vệ sinh', parentCode: 'C' },
  { code: '20290', level: 4, name: 'Sản xuất sản phẩm hóa chất khác chưa được phân vào đâu', parentCode: 'C' },
  { code: '20300', level: 4, name: 'Sản xuất sợi nhân tạo', parentCode: 'C' },
  { code: '21000', level: 4, name: 'Sản xuất thuốc, hóa dược và dược liệu', parentCode: 'C' },
  { code: '22110', level: 4, name: 'Sản xuất săm, lốp cao su; tái sinh cao su', parentCode: 'C' },
  { code: '22120', level: 4, name: 'Sản xuất sản phẩm khác từ cao su', parentCode: 'C' },
  { code: '22200', level: 4, name: 'Sản xuất sản phẩm từ chất dẻo', parentCode: 'C' },
  { code: '23100', level: 4, name: 'Sản xuất thủy tinh và sản phẩm từ thủy tinh', parentCode: 'C' },
  { code: '23910', level: 4, name: 'Sản xuất gạch, ngói, đá lát và đá xây dựng khác', parentCode: 'C' },
  { code: '23920', level: 4, name: 'Sản xuất xi măng, vôi và thạch cao', parentCode: 'C' },
  { code: '23930', level: 4, name: 'Sản xuất bê tông và các sản phẩm từ bê tông, xi măng và thạch cao', parentCode: 'C' },
  { code: '24100', level: 4, name: 'Sản xuất sắt, thép, gang', parentCode: 'C' },
  { code: '24200', level: 4, name: 'Sản xuất kim loại quý và kim loại màu', parentCode: 'C' },
  { code: '24310', level: 4, name: 'Đúc kim loại', parentCode: 'C' },
  { code: '25110', level: 4, name: 'Sản xuất kết cấu kim loại', parentCode: 'C' },
  { code: '25120', level: 4, name: 'Sản xuất thùng, bể chứa và container bằng kim loại', parentCode: 'C' },
  { code: '25130', level: 4, name: 'Sản xuất nồi hơi', parentCode: 'C' },
  { code: '25200', level: 4, name: 'Sản xuất vũ khí và đạn dược', parentCode: 'C' },
  { code: '25910', level: 4, name: 'Rèn, dập, ép và cán kim loại; luyện bột', parentCode: 'C' },
  { code: '25920', level: 4, name: 'Xử lý và phủ kim loại; gia công cơ khí', parentCode: 'C' },
  { code: '25930', level: 4, name: 'Sản xuất dao kéo, dụng cụ cầm tay và đồ kim loại thông dụng', parentCode: 'C' },
  { code: '25990', level: 4, name: 'Sản xuất sản phẩm khác bằng kim loại chưa được phân vào đâu', parentCode: 'C' },
  { code: '26100', level: 4, name: 'Sản xuất linh kiện điện tử', parentCode: 'C' },
  { code: '26200', level: 4, name: 'Sản xuất máy vi tính và thiết bị ngoại vi', parentCode: 'C' },
  { code: '26300', level: 4, name: 'Sản xuất thiết bị truyền thông', parentCode: 'C' },
  { code: '26400', level: 4, name: 'Sản xuất sản phẩm điện tử dân dụng', parentCode: 'C' },
  { code: '26510', level: 4, name: 'Sản xuất thiết bị đo lường, kiểm tra, định hướng và điều khiển', parentCode: 'C' },
  { code: '26520', level: 4, name: 'Sản xuất đồng hồ', parentCode: 'C' },
  { code: '26600', level: 4, name: 'Sản xuất thiết bị bức xạ và thiết bị điện tử trong y học', parentCode: 'C' },
  { code: '26700', level: 4, name: 'Sản xuất thiết bị quang học và thiết bị chụp ảnh', parentCode: 'C' },
  { code: '26800', level: 4, name: 'Sản xuất băng, đĩa từ tính và quang học', parentCode: 'C' },
  { code: '27100', level: 4, name: 'Sản xuất động cơ, máy phát, máy biến áp, thiết bị phân phối và điều khiển điện', parentCode: 'C' },
  { code: '27200', level: 4, name: 'Sản xuất ắc quy, pin và tích điện', parentCode: 'C' },
  { code: '27310', level: 4, name: 'Sản xuất cáp quang và sợi cáp quang', parentCode: 'C' },
  { code: '27320', level: 4, name: 'Sản xuất dây và thiết bị dây dẫn điện khác', parentCode: 'C' },
  { code: '27400', level: 4, name: 'Sản xuất thiết bị chiếu sáng', parentCode: 'C' },
  { code: '27500', level: 4, name: 'Sản xuất đồ điện gia dụng', parentCode: 'C' },
  { code: '27900', level: 4, name: 'Sản xuất thiết bị điện khác', parentCode: 'C' },
  { code: '28110', level: 4, name: 'Sản xuất máy dùng cho khai thác mỏ và xây dựng', parentCode: 'C' },
  { code: '28120', level: 4, name: 'Sản xuất máy chế biến thực phẩm, đồ uống, thuốc lá', parentCode: 'C' },
  { code: '28130', level: 4, name: 'Sản xuất máy dệt, may và da', parentCode: 'C' },
  { code: '28140', level: 4, name: 'Sản xuất máy nông, lâm nghiệp', parentCode: 'C' },
  { code: '28150', level: 4, name: 'Sản xuất máy công cụ và máy gia công kim loại', parentCode: 'C' },
  { code: '28160', level: 4, name: 'Sản xuất máy và thiết bị ngành in và sao chụp', parentCode: 'C' },
  { code: '28170', level: 4, name: 'Sản xuất thiết bị nâng hạ và băng tải', parentCode: 'C' },
  { code: '28180', level: 4, name: 'Sản xuất máy và thiết bị văn phòng', parentCode: 'C' },
  { code: '28190', level: 4, name: 'Sản xuất máy chuyên dụng khác', parentCode: 'C' },
  { code: '28210', level: 4, name: 'Sản xuất máy nén khí và bơm', parentCode: 'C' },
  { code: '28220', level: 4, name: 'Sản xuất quạt và thiết bị điều hòa không khí', parentCode: 'C' },
  { code: '28230', level: 4, name: 'Sản xuất máy và thiết bị làm lạnh công nghiệp', parentCode: 'C' },
  { code: '28240', level: 4, name: 'Sản xuất máy đúc, băng chuyền và thiết bị tự động hóa', parentCode: 'C' },
  { code: '28250', level: 4, name: 'Sản xuất máy và thiết bị lọc, tinh chế', parentCode: 'C' },
  { code: '28260', level: 4, name: 'Sản xuất máy và thiết bị đóng gói, chiết rót', parentCode: 'C' },
  { code: '28290', level: 4, name: 'Sản xuất máy chuyên dụng chưa được phân vào đâu', parentCode: 'C' },
  { code: '29100', level: 4, name: 'Sản xuất ô tô và xe có động cơ khác', parentCode: 'C' },
  { code: '29200', level: 4, name: 'Sản xuất thân xe, rơ moóc, bán moóc', parentCode: 'C' },
  { code: '29300', level: 4, name: 'Sản xuất phụ tùng và bộ phận phụ trợ cho ô tô và xe có động cơ khác', parentCode: 'C' },
  { code: '30110', level: 4, name: 'Đóng tàu và cấu kiện nổi', parentCode: 'C' },
  { code: '30120', level: 4, name: 'Đóng thuyền, xuồng thể thao và giải trí', parentCode: 'C' },
  { code: '30200', level: 4, name: 'Sản xuất đầu máy, toa xe và thiết bị đường sắt', parentCode: 'C' },
  { code: '30300', level: 4, name: 'Sản xuất máy bay và thiết bị vũ trụ', parentCode: 'C' },
  { code: '30400', level: 4, name: 'Sản xuất xe quân sự chiến đấu', parentCode: 'C' },
  { code: '30910', level: 4, name: 'Sản xuất mô tô, xe máy', parentCode: 'C' },
  { code: '30920', level: 4, name: 'Sản xuất xe đạp và xe lăn', parentCode: 'C' },
  { code: '30990', level: 4, name: 'Sản xuất phương tiện vận tải chưa được phân vào đâu', parentCode: 'C' },
  { code: '31000', level: 4, name: 'Sản xuất giường, tủ, bàn, ghế', parentCode: 'C' },
  { code: '32110', level: 4, name: 'Sản xuất đồ trang sức và các sản phẩm từ kim loại quý', parentCode: 'C' },
  { code: '32120', level: 4, name: 'Sản xuất nhạc cụ', parentCode: 'C' },
  { code: '32200', level: 4, name: 'Sản xuất dụng cụ thể thao', parentCode: 'C' },
  { code: '32300', level: 4, name: 'Sản xuất đồ chơi trẻ em', parentCode: 'C' },
  { code: '32400', level: 4, name: 'Sản xuất thiết bị y tế, dụng cụ chỉnh hình và phục hồi chức năng', parentCode: 'C' },
  { code: '32500', level: 4, name: 'Sản xuất đồ dùng cho nhà bếp, bàn ăn và đồ thủy tinh', parentCode: 'C' },
  { code: '32900', level: 4, name: 'Sản xuất sản phẩm chưa được phân vào đâu', parentCode: 'C' },
  { code: '41010', level: 4, name: 'Xây dựng nhà các loại', parentCode: 'F' },
  { code: '41020', level: 4, name: 'Xây dựng công trình kỹ thuật dân dụng', parentCode: 'F' },
  { code: '41030', level: 4, name: 'Phá dỡ và chuẩn bị mặt bằng', parentCode: 'F' },
  { code: '42100', level: 4, name: 'Xây dựng công trình đường bộ', parentCode: 'F' },
  { code: '42210', level: 4, name: 'Xây dựng công trình đường sắt', parentCode: 'F' },
  { code: '42220', level: 4, name: 'Xây dựng công trình cầu, cảng, đê, đập', parentCode: 'F' },
  { code: '42230', level: 4, name: 'Xây dựng công trình điện', parentCode: 'F' },
  { code: '42240', level: 4, name: 'Xây dựng công trình cấp, thoát nước', parentCode: 'F' },
  { code: '42290', level: 4, name: 'Xây dựng công trình kỹ thuật dân dụng khác', parentCode: 'F' },
  { code: '43110', level: 4, name: 'Phá dỡ', parentCode: 'F' },
  { code: '43120', level: 4, name: 'Chuẩn bị mặt bằng', parentCode: 'F' },
  { code: '43210', level: 4, name: 'Lắp đặt hệ thống điện', parentCode: 'F' },
  { code: '43220', level: 4, name: 'Lắp đặt hệ thống cấp, thoát nước, sưởi và điều hòa không khí', parentCode: 'F' },
  { code: '43290', level: 4, name: 'Lắp đặt hệ thống xây dựng khác', parentCode: 'F' },
  { code: '43300', level: 4, name: 'Hoàn thiện công trình xây dựng', parentCode: 'F' },
  { code: '43900', level: 4, name: 'Hoạt động xây dựng chuyên dụng khác', parentCode: 'F' },
  { code: '45110', level: 4, name: 'Bán buôn ô tô và xe có động cơ khác', parentCode: 'G' },
  { code: '45120', level: 4, name: 'Bán lẻ ô tô và xe có động cơ khác', parentCode: 'G' },
  { code: '45200', level: 4, name: 'Bảo dưỡng, sửa chữa ô tô và xe có động cơ khác', parentCode: 'G' },
  { code: '45300', level: 4, name: 'Bán phụ tùng và bộ phận phụ trợ của ô tô và xe có động cơ khác', parentCode: 'G' },
  { code: '45410', level: 4, name: 'Bán buôn mô tô, xe máy', parentCode: 'G' },
  { code: '45420', level: 4, name: 'Bán lẻ mô tô, xe máy', parentCode: 'G' },
  { code: '45430', level: 4, name: 'Bảo dưỡng, sửa chữa mô tô, xe máy', parentCode: 'G' },
  { code: '46100', level: 4, name: 'Bán buôn tổng hợp', parentCode: 'G' },
  { code: '46200', level: 4, name: 'Bán buôn nông, lâm sản nguyên liệu và động vật sống', parentCode: 'G' },
  { code: '46300', level: 4, name: 'Bán buôn thực phẩm, đồ uống, thuốc lá', parentCode: 'G' },
  { code: '46410', level: 4, name: 'Bán buôn vải, hàng may sẵn, giày dép', parentCode: 'G' },
  { code: '46420', level: 4, name: 'Bán buôn đồ dùng gia đình', parentCode: 'G' },
  { code: '46430', level: 4, name: 'Bán buôn mỹ phẩm, nước hoa, xà phòng, chất tẩy rửa', parentCode: 'G' },
  { code: '46440', level: 4, name: 'Bán buôn đồ trang sức, đồng hồ', parentCode: 'G' },
  { code: '46450', level: 4, name: 'Bán buôn đồ điện, điện tử, viễn thông', parentCode: 'G' },
  { code: '46460', level: 4, name: 'Bán buôn máy móc, thiết bị văn phòng', parentCode: 'G' },
  { code: '46470', level: 4, name: 'Bán buôn vật liệu xây dựng', parentCode: 'G' },
  { code: '46480', level: 4, name: 'Bán buôn kim loại và quặng kim loại', parentCode: 'G' },
  { code: '46510', level: 4, name: 'Bán buôn máy nông, lâm nghiệp', parentCode: 'G' },
  { code: '46520', level: 4, name: 'Bán buôn máy công cụ và máy chuyên dụng', parentCode: 'G' },
  { code: '46530', level: 4, name: 'Bán buôn máy móc, thiết bị khai thác mỏ, xây dựng', parentCode: 'G' },
  { code: '46540', level: 4, name: 'Bán buôn máy móc, thiết bị điện, điện tử', parentCode: 'G' },
  { code: '46590', level: 4, name: 'Bán buôn máy móc, thiết bị chuyên dụng khác', parentCode: 'G' },
  { code: '46610', level: 4, name: 'Bán buôn nhiên liệu rắn, lỏng, khí', parentCode: 'G' },
  { code: '46620', level: 4, name: 'Bán buôn hóa chất', parentCode: 'G' },
  { code: '46630', level: 4, name: 'Bán buôn phân bón, thuốc bảo vệ thực vật', parentCode: 'G' },
  { code: '46640', level: 4, name: 'Bán buôn đồ uống có cồn', parentCode: 'G' },
  { code: '46650', level: 4, name: 'Bán buôn sách, báo, tạp chí, văn phòng phẩm', parentCode: 'G' },
  { code: '46690', level: 4, name: 'Bán buôn chuyên doanh khác chưa được phân vào đâu', parentCode: 'G' },
  { code: '47110', level: 4, name: 'Bán lẻ lương thực, thực phẩm, đồ uống trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47120', level: 4, name: 'Bán lẻ hàng hóa khác trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47190', level: 4, name: 'Bán lẻ hình thức khác', parentCode: 'G' },
  { code: '47210', level: 4, name: 'Bán lẻ thực phẩm trong các cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47220', level: 4, name: 'Bán lẻ đồ uống trong các cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47230', level: 4, name: 'Bán lẻ thuốc lá, thuốc lào trong các cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47300', level: 4, name: 'Bán lẻ nhiên liệu động cơ trong các cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47410', level: 4, name: 'Bán lẻ máy vi tính, thiết bị ngoại vi, phần mềm trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47420', level: 4, name: 'Bán lẻ thiết bị viễn thông trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47510', level: 4, name: 'Bán lẻ hàng may mặc trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47520', level: 4, name: 'Bán lẻ giày dép, túi xách trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47530', level: 4, name: 'Bán lẻ đồ điện gia dụng trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47540', level: 4, name: 'Bán lẻ đồ dùng gia đình, đồ gỗ, đèn và thiết bị chiếu sáng trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47550', level: 4, name: 'Bán lẻ đồ trang sức, đồng hồ trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47560', level: 4, name: 'Bán lẻ đồ thể thao, dụng cụ thể thao trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47570', level: 4, name: 'Bán lẻ sách, báo, tạp chí, văn phòng phẩm trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47580', level: 4, name: 'Bán lẻ mỹ phẩm, nước hoa, xà phòng, chất tẩy rửa trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47590', level: 4, name: 'Bán lẻ hàng hóa khác mới trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47610', level: 4, name: 'Bán lẻ hàng đã qua sử dụng trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47620', level: 4, name: 'Bán lẻ phụ tùng ô tô, mô tô, xe máy trong cửa hàng chuyên doanh', parentCode: 'G' },
  { code: '47710', level: 4, name: 'Bán lẻ trong siêu thị', parentCode: 'G' },
  { code: '47720', level: 4, name: 'Bán lẻ trong cửa hàng tổng hợp', parentCode: 'G' },
  { code: '47730', level: 4, name: 'Bán lẻ theo đơn đặt hàng', parentCode: 'G' },
  { code: '47740', level: 4, name: 'Bán lẻ qua bưu điện, internet', parentCode: 'G' },
  { code: '47810', level: 4, name: 'Bán lẻ lưu động', parentCode: 'G' },
  { code: '47820', level: 4, name: 'Bán lẻ tại chợ', parentCode: 'G' },
  { code: '47910', level: 4, name: 'Bán lẻ hình thức khác chưa được phân vào đâu', parentCode: 'G' },
  { code: '49110', level: 4, name: 'Vận tải hành khách đường sắt', parentCode: 'H' },
  { code: '49120', level: 4, name: 'Vận tải hàng hóa đường sắt', parentCode: 'H' },
  { code: '49211', level: 4, name: 'Vận tải hành khách đường bộ nội thành, ngoại thành', parentCode: 'H' },
  { code: '49212', level: 4, name: 'Vận tải hành khách đường bộ liên tỉnh', parentCode: 'H' },
  { code: '49213', level: 4, name: 'Vận tải hành khách đường bộ quốc tế', parentCode: 'H' },
  { code: '49220', level: 4, name: 'Vận tải hàng hóa bằng đường bộ', parentCode: 'H' },
  { code: '49300', level: 4, name: 'Vận tải đường ống', parentCode: 'H' },
  { code: '50110', level: 4, name: 'Vận tải hành khách đường thủy nội địa', parentCode: 'H' },
  { code: '50120', level: 4, name: 'Vận tải hàng hóa đường thủy nội địa', parentCode: 'H' },
  { code: '50210', level: 4, name: 'Vận tải hành khách đường biển', parentCode: 'H' },
  { code: '50220', level: 4, name: 'Vận tải hàng hóa đường biển', parentCode: 'H' },
  { code: '51100', level: 4, name: 'Vận tải hành khách hàng không', parentCode: 'H' },
  { code: '51200', level: 4, name: 'Vận tải hàng hóa hàng không', parentCode: 'H' },
  { code: '52100', level: 4, name: 'Kho bãi và lưu giữ hàng hóa', parentCode: 'H' },
  { code: '52210', level: 4, name: 'Dịch vụ hỗ trợ vận tải đường bộ', parentCode: 'H' },
  { code: '52220', level: 4, name: 'Dịch vụ hỗ trợ vận tải đường thủy', parentCode: 'H' },
  { code: '52230', level: 4, name: 'Dịch vụ hỗ trợ vận tải hàng không', parentCode: 'H' },
  { code: '52240', level: 4, name: 'Hoạt động bốc xếp hàng hóa', parentCode: 'H' },
  { code: '52250', level: 4, name: 'Hoạt động đại lý du lịch, điều hành tour', parentCode: 'H' },
  { code: '52260', level: 4, name: 'Dịch vụ hỗ trợ vận tải khác', parentCode: 'H' },
  { code: '53100', level: 4, name: 'Bưu chính', parentCode: 'H' },
  { code: '53200', level: 4, name: 'Chuyển phát', parentCode: 'H' },
  { code: '55100', level: 4, name: 'Dịch vụ lưu trú ngắn ngày', parentCode: 'I' },
  { code: '55200', level: 4, name: 'Khu nghỉ dưỡng, cắm trại', parentCode: 'I' },
  { code: '55300', level: 4, name: 'Nhà hàng và dịch vụ ăn uống phục vụ lưu động', parentCode: 'I' },
  { code: '55900', level: 4, name: 'Dịch vụ lưu trú khác', parentCode: 'I' },
  { code: '56100', level: 4, name: 'Nhà hàng và các dịch vụ ăn uống phục vụ lưu động', parentCode: 'I' },
  { code: '56210', level: 4, name: 'Dịch vụ cung cấp suất ăn sẵn', parentCode: 'I' },
  { code: '56220', level: 4, name: 'Dịch vụ ăn uống theo hợp đồng', parentCode: 'I' },
  { code: '56290', level: 4, name: 'Dịch vụ ăn uống khác', parentCode: 'I' },
  { code: '58110', level: 4, name: 'Xuất bản sách', parentCode: 'J' },
  { code: '58120', level: 4, name: 'Xuất bản danh bạ, bản tin', parentCode: 'J' },
  { code: '58130', level: 4, name: 'Xuất bản báo, tạp chí, tập san', parentCode: 'J' },
  { code: '58140', level: 4, name: 'Xuất bản phần mềm', parentCode: 'J' },
  { code: '58190', level: 4, name: 'Xuất bản khác', parentCode: 'J' },
  { code: '59110', level: 4, name: 'Sản xuất phim điện ảnh, phim video', parentCode: 'J' },
  { code: '59120', level: 4, name: 'Sản xuất chương trình truyền hình', parentCode: 'J' },
  { code: '59130', level: 4, name: 'Phân phối phim, băng đĩa', parentCode: 'J' },
  { code: '59140', level: 4, name: 'Chiếu phim', parentCode: 'J' },
  { code: '59200', level: 4, name: 'Hoạt động thu âm và xuất bản âm nhạc', parentCode: 'J' },
  { code: '60100', level: 4, name: 'Phát thanh', parentCode: 'J' },
  { code: '60200', level: 4, name: 'Hoạt động truyền hình', parentCode: 'J' },
  { code: '61100', level: 4, name: 'Viễn thông có dây', parentCode: 'J' },
  { code: '61200', level: 4, name: 'Viễn thông không dây', parentCode: 'J' },
  { code: '61300', level: 4, name: 'Viễn thông vệ tinh', parentCode: 'J' },
  { code: '61900', level: 4, name: 'Viễn thông khác', parentCode: 'J' },
  { code: '62010', level: 4, name: 'Lập trình máy vi tính', parentCode: 'J' },
  { code: '62020', level: 4, name: 'Tư vấn máy vi tính và quản trị hệ thống máy vi tính', parentCode: 'J' },
  { code: '62090', level: 4, name: 'Hoạt động dịch vụ công nghệ thông tin khác', parentCode: 'J' },
  { code: '63110', level: 4, name: 'Xử lý dữ liệu, cho thuê và các hoạt động liên quan', parentCode: 'J' },
  { code: '63120', level: 4, name: 'Cổng thông tin và các nền tảng trực tuyến', parentCode: 'J' },
  { code: '63910', level: 4, name: 'Dịch vụ thông tin khác', parentCode: 'J' },
  { code: '63990', level: 4, name: 'Hoạt động thông tin chưa được phân vào đâu', parentCode: 'J' },
  { code: '64110', level: 4, name: 'Ngân hàng trung ương', parentCode: 'K' },
  { code: '64190', level: 4, name: 'Trung gian tài chính tiền tệ khác', parentCode: 'K' },
  { code: '64200', level: 4, name: 'Hoạt động công ty tài chính, công ty đầu tư', parentCode: 'K' },
  { code: '64300', level: 4, name: 'Quỹ tín thác, quỹ tài chính và các tổ chức tài chính tương tự', parentCode: 'K' },
  { code: '64910', level: 4, name: 'Cho thuê tài chính', parentCode: 'K' },
  { code: '64920', level: 4, name: 'Dịch vụ tài chính khác', parentCode: 'K' },
  { code: '65110', level: 4, name: 'Bảo hiểm nhân thọ', parentCode: 'K' },
  { code: '65120', level: 4, name: 'Bảo hiểm phi nhân thọ', parentCode: 'K' },
  { code: '65200', level: 4, name: 'Tái bảo hiểm', parentCode: 'K' },
  { code: '65300', level: 4, name: 'Quỹ hưu trí, bảo hiểm xã hội', parentCode: 'K' },
  { code: '66110', level: 4, name: 'Quản lý thị trường tài chính', parentCode: 'K' },
  { code: '66120', level: 4, name: 'Môi giới chứng khoán và quỹ', parentCode: 'K' },
  { code: '66190', level: 4, name: 'Hoạt động dịch vụ tài chính khác', parentCode: 'K' },
  { code: '66210', level: 4, name: 'Định giá bảo hiểm', parentCode: 'K' },
  { code: '66290', level: 4, name: 'Hoạt động hỗ trợ bảo hiểm khác', parentCode: 'K' },
  { code: '68100', level: 4, name: 'Kinh doanh bất động sản', parentCode: 'L' },
  { code: '68201', level: 4, name: 'Môi giới bất động sản', parentCode: 'L' },
  { code: '68202', level: 4, name: 'Định giá bất động sản', parentCode: 'L' },
  { code: '68209', level: 4, name: 'Dịch vụ bất động sản khác', parentCode: 'L' },
  { code: '69100', level: 4, name: 'Hoạt động của luật sư', parentCode: 'M' },
  { code: '69200', level: 4, name: 'Hoạt động kiểm toán, kế toán', parentCode: 'M' },
  { code: '70100', level: 4, name: 'Hoạt động của trụ sở văn phòng', parentCode: 'M' },
  { code: '70200', level: 4, name: 'Hoạt động quản lý và tư vấn quản lý', parentCode: 'M' },
  { code: '71100', level: 4, name: 'Hoạt động kiến trúc; tư vấn kỹ thuật', parentCode: 'M' },
  { code: '71200', level: 4, name: 'Kiểm tra và phân tích kỹ thuật', parentCode: 'M' },
  { code: '72100', level: 4, name: 'Nghiên cứu khoa học và phát triển công nghệ', parentCode: 'M' },
  { code: '72200', level: 4, name: 'Nghiên cứu khoa học xã hội và nhân văn', parentCode: 'M' },
  { code: '73100', level: 4, name: 'Quảng cáo', parentCode: 'M' },
  { code: '73200', level: 4, name: 'Nghiên cứu thị trường và thăm dò dư luận', parentCode: 'M' },
  { code: '74100', level: 4, name: 'Hoạt động thiết kế chuyên dụng', parentCode: 'M' },
  { code: '74200', level: 4, name: 'Hoạt động nhiếp ảnh', parentCode: 'M' },
  { code: '74300', level: 4, name: 'Dịch thuật và phiên dịch', parentCode: 'M' },
  { code: '74900', level: 4, name: 'Hoạt động chuyên môn, khoa học và công nghệ khác chưa được phân vào đâu', parentCode: 'M' },
  { code: '77100', level: 4, name: 'Cho thuê xe có động cơ', parentCode: 'N' },
  { code: '77210', level: 4, name: 'Cho thuêu đồ dùng giải trí, thể thao', parentCode: 'N' },
  { code: '77220', level: 4, name: 'Cho thuê băng đĩa', parentCode: 'N' },
  { code: '77290', level: 4, name: 'Cho thuê đồ dùng cá nhân và đồ gia dụng khác', parentCode: 'N' },
  { code: '77300', level: 4, name: 'Cho thuê máy móc, thiết bị', parentCode: 'N' },
  { code: '77400', level: 4, name: 'Cho thuê tài sản vô hình', parentCode: 'N' },
  { code: '78100', level: 4, name: 'Dịch vụ giới thiệu việc làm', parentCode: 'N' },
  { code: '78200', level: 4, name: 'Cung ứng lao động tạm thời', parentCode: 'N' },
  { code: '78300', level: 4, name: 'Dịch vụ nhân sự khác', parentCode: 'N' },
  { code: '79110', level: 4, name: 'Điều hành tour du lịch', parentCode: 'N' },
  { code: '79120', level: 4, name: 'Dịch vụ đặt chỗ và dịch vụ hỗ trợ du lịch khác', parentCode: 'N' },
  { code: '79900', level: 4, name: 'Dịch vụ đặt vé và dịch vụ hỗ trợ du lịch khác', parentCode: 'N' },
  { code: '80100', level: 4, name: 'Dịch vụ bảo vệ', parentCode: 'N' },
  { code: '80200', level: 4, name: 'Dịch vụ điều tra', parentCode: 'N' },
  { code: '80300', level: 4, name: 'Dịch vụ hỗ trợ giám sát', parentCode: 'N' },
  { code: '81100', level: 4, name: 'Dịch vụ hỗ trợ tổng hợp', parentCode: 'N' },
  { code: '81210', level: 4, name: 'Vệ sinh chung nhà cửa', parentCode: 'N' },
  { code: '81220', level: 4, name: 'Vệ sinh công nghiệp', parentCode: 'N' },
  { code: '81290', level: 4, name: 'Hoạt động vệ sinh khác', parentCode: 'N' },
  { code: '81300', level: 4, name: 'Dịch vụ chăm sóc và duy trì cảnh quan', parentCode: 'N' },
  { code: '82110', level: 4, name: 'Dịch vụ hành chính văn phòng', parentCode: 'N' },
  { code: '82190', level: 4, name: 'Dịch vụ sao chụp, chuẩn bị tài liệu', parentCode: 'N' },
  { code: '82200', level: 4, name: 'Dịch vụ tổng đài', parentCode: 'N' },
  { code: '82300', level: 4, name: 'Tổ chức hội chợ, triển lãm', parentCode: 'N' },
  { code: '82910', level: 4, name: 'Dịch vụ thu hồi nợ', parentCode: 'N' },
  { code: '82920', level: 4, name: 'Dịch vụ đóng gói', parentCode: 'N' },
  { code: '82990', level: 4, name: 'Dịch vụ hỗ trợ kinh doanh khác chưa được phân vào đâu', parentCode: 'N' },
  { code: '85100', level: 4, name: 'Giáo dục mầm non', parentCode: 'P' },
  { code: '85210', level: 4, name: 'Giáo dục tiểu học', parentCode: 'P' },
  { code: '85220', level: 4, name: 'Giáo dục trung học cơ sở', parentCode: 'P' },
  { code: '85310', level: 4, name: 'Giáo dục trung học phổ thông', parentCode: 'P' },
  { code: '85320', level: 4, name: 'Giáo dục nghề nghiệp', parentCode: 'P' },
  { code: '85410', level: 4, name: 'Giáo dục đại học', parentCode: 'P' },
  { code: '85420', level: 4, name: 'Giáo dục sau đại học', parentCode: 'P' },
  { code: '85510', level: 4, name: 'Đào tạo thể thao và giải trí', parentCode: 'P' },
  { code: '85520', level: 4, name: 'Đào tạo văn hóa nghệ thuật', parentCode: 'P' },
  { code: '85590', level: 4, name: 'Giáo dục khác chưa được phân vào đâu', parentCode: 'P' },
  { code: '85600', level: 4, name: 'Dịch vụ hỗ trợ giáo dục', parentCode: 'P' },
  { code: '86101', level: 4, name: 'Bệnh viện đa khoa', parentCode: 'Q' },
  { code: '86102', level: 4, name: 'Bệnh viện chuyên khoa', parentCode: 'Q' },
  { code: '86201', level: 4, name: 'Phòng khám đa khoa', parentCode: 'Q' },
  { code: '86202', level: 4, name: 'Phòng khám chuyên khoa', parentCode: 'Q' },
  { code: '86203', level: 4, name: 'Phòng khám nha khoa', parentCode: 'Q' },
  { code: '86901', level: 4, name: 'Dịch vụ y tế khác', parentCode: 'Q' },
  { code: '86902', level: 4, name: 'Dịch vụ chăm sóc sức khỏe tại nhà', parentCode: 'Q' },
  { code: '87100', level: 4, name: 'Điều dưỡng tập trung', parentCode: 'Q' },
  { code: '87200', level: 4, name: 'Chăm sóc người khuyết tật, người già', parentCode: 'Q' },
  { code: '87300', level: 4, name: 'Chăm sóc trẻ em tại cơ sở', parentCode: 'Q' },
  { code: '87900', level: 4, name: 'Dịch vụ trợ giúp xã hội khác', parentCode: 'Q' },
  { code: '90001', level: 4, name: 'Biểu diễn nghệ thuật', parentCode: 'R' },
  { code: '90002', level: 4, name: 'Hoạt động hỗ trợ biểu diễn', parentCode: 'R' },
  { code: '90003', level: 4, name: 'Hoạt động văn hóa nghệ thuật khác', parentCode: 'R' },
  { code: '91010', level: 4, name: 'Hoạt động thư viện', parentCode: 'R' },
  { code: '91020', level: 4, name: 'Hoạt động bảo tàng', parentCode: 'R' },
  { code: '91030', level: 4, name: 'Quản lý di tích lịch sử, danh lam thắng cảnh', parentCode: 'R' },
  { code: '92000', level: 4, name: 'Hoạt động xổ số, cá cược và đánh bạc', parentCode: 'R' },
  { code: '93110', level: 4, name: 'Hoạt động thể thao', parentCode: 'R' },
  { code: '93120', level: 4, name: 'Hoạt động câu lạc bộ thể thao', parentCode: 'R' },
  { code: '93190', level: 4, name: 'Hoạt động thể thao khác', parentCode: 'R' },
  { code: '93210', level: 4, name: 'Hoạt động vui chơi giải trí công viên', parentCode: 'R' },
  { code: '93290', level: 4, name: 'Hoạt động vui chơi giải trí khác', parentCode: 'R' },
  { code: '94110', level: 4, name: 'Hoạt động của hiệp hội kinh doanh', parentCode: 'S' },
  { code: '94120', level: 4, name: 'Hoạt động của hiệp hội nghề nghiệp', parentCode: 'S' },
  { code: '94200', level: 4, name: 'Hoạt động của công đoàn', parentCode: 'S' },
  { code: '94910', level: 4, name: 'Hoạt động của tổ chức tôn giáo', parentCode: 'S' },
  { code: '94990', level: 4, name: 'Hoạt động của tổ chức khác', parentCode: 'S' },
  { code: '95110', level: 4, name: 'Sửa chữa máy vi tính, thiết bị ngoại vi', parentCode: 'S' },
  { code: '95120', level: 4, name: 'Sửa chữa thiết bị viễn thông', parentCode: 'S' },
  { code: '95210', level: 4, name: 'Sửa chữa đồ điện gia dụng', parentCode: 'S' },
  { code: '95220', level: 4, name: 'Sửa chữa giày, dép, đồ da', parentCode: 'S' },
  { code: '95230', level: 4, name: 'Sửa chữa đồ gỗ, nội thất', parentCode: 'S' },
  { code: '95240', level: 4, name: 'Sửa chữa đồ trang sức, đồng hồ', parentCode: 'S' },
  { code: '95250', level: 4, name: 'Sửa chữa xe đạp, xe lăn', parentCode: 'S' },
  { code: '95290', level: 4, name: 'Sửa chữa đồ dùng cá nhân và đồ gia dụng khác', parentCode: 'S' },
  { code: '96010', level: 4, name: 'Giặt là, làm sạch', parentCode: 'S' },
  { code: '96020', level: 4, name: 'Làm tóc, làm đẹp', parentCode: 'S' },
  { code: '96030', level: 4, name: 'Dịch vụ tang lễ', parentCode: 'S' },
  { code: '96090', level: 4, name: 'Dịch vụ cá nhân khác', parentCode: 'S' },
];

export function seedVSICData(db: Database): void {
  const existing = db.prepare('SELECT COUNT(*) as c FROM vsic_reference').get() as { c: number };
  if (existing.c > 0) return;

  const insert = db.prepare(
    'INSERT INTO vsic_reference (code, level, name, parent_code) VALUES (?, ?, ?, ?)',
  );
  const tx = db.transaction((entries: VSICEntry[]) => {
    for (const e of entries) {
      insert.run(e.code, e.level, e.name, e.parentCode);
    }
  });
  tx(VSIC_SEED_DATA);
  console.log(`Seeded ${VSIC_SEED_DATA.length} VSIC codes`);
}
